language: node_js
node_js:
  -  "0.12"
before_script:
  - npm install gulp
script:
  - gulp build

deploy:
  provider: heroku
  app: 
    master: pdes-flappernews-en-clase
    cdeployment: pdes-flappernews-en-clase
  api_key:
    secure: $HEROKU_API_KEY
